mi-pasteleria/mi-pasteleria/Models/Order.cs
using System;

namespace mi_pasteleria.Models
{
    public class Order
    {
        public int id { get; set; }
        public String orderType { get; set; }
        public String productDesc { get; set; }
        public String flavor1 { get; set; }
        public String flavor2 { get; set; }
        public String cover { get; set; }
        public String addOn1 { get; set; }
        public String addOn2 { get; set; }
        public String clientName { get; set; }
        public String clientPhone { get; set; }
        public String clientSchedule { get; set; }
        public String status { get; set; }
    }
}

mi-pasteleria/mi-pasteleria/Models/Stock.cs
using System;

namespace mi_pasteleria.Models
{
    public class Stock
    {
        public int id { get; set; }
        public String name { get; set; }
        public String productType { get; set; }
        public String quantity { get; set; }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Baker/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Baker
{
    public class OrderModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Baker/Stock.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Baker
{
    public class StockModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Complement.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Catalogue
{
    public class ComplementModel : PageModel
    {
        public void OnGet(int id)
        {
            switch (id)
            {
                case 1:
                    ViewData["PastelSeleccionado"] = "Tentación de mango";
                    break;
                case 2:
                    ViewData["PastelSeleccionado"] = "Tentación de fresa";
                    break;
                case 3:
                    ViewData["PastelSeleccionado"] = "Tentación de mango-fresa";
                    break;
                case 4:
                    ViewData["PastelSeleccionado"] = "Tentación de Nutella®";
                    break;
                case 5:
                    ViewData["PastelSeleccionado"] = "Nevado de fresa";
                    break;
                case 6:
                    ViewData["PastelSeleccionado"] = "Nevado de nuez";
                    break;
                case 7:
                    ViewData["PastelSeleccionado"] = "Nevado MilkyWay®";
                    break;
                case 8:
                    ViewData["PastelSeleccionado"] = "Nevado Oreo®";
                    break;
                case 9:
                    ViewData["PastelSeleccionado"] = "Chocolate tortuga";
                    break;
                case 10:
                    ViewData["PastelSeleccionado"] = "Chocolate alemán";
                    break;
                case 11:
                    ViewData["PastelSeleccionado"] = "Chocolate bombon";
                    break;
                case 12:
                    ViewData["PastelSeleccionado"] = "Chocolate Carlos V®";
                    break;
            }
        }

        public IActionResult OnPostQuote(string selected)
        {
            return RedirectToPage("/Catalogue/Quote", new
            {
                selected = selected
            });
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Catalogue
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Ordered.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Catalogue
{
    public class OrderedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Catalogue
{
    public class PaymentModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostOrdered()
        {
            return RedirectToPage("/Catalogue/Ordered");
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Quote.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Catalogue
{
    public class QuoteModel : PageModel
    {
        public void OnGet(string selected)
        {
            ViewData["PastelSeleccionado"] = selected;
        }

        public IActionResult OnPostPayment()
        {
            return RedirectToPage("/Catalogue/Payment");
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace mi_pasteleria.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace mi_pasteleria.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Make/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Make
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostQuote()
        {
            return RedirectToPage("/Make/Quote");
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Make/Ordered.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Make
{
    public class OrderedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Make/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Make
{
    public class PaymentModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostOrdered()
        {
            return RedirectToPage("/Make/Ordered");
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Make/Quote.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mi_pasteleria.Pages.Make
{
    public class QuoteModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostPayment()
        {
            return RedirectToPage("/Make/Payment");
        }
    }
}

mi-pasteleria/mi-pasteleria/Pages/Baker/Stock.cshtml
@page
@using Models
@model StockModel
@{
    ViewBag.Title = "Stock";
    List<Stock> stocks = new List<Stock> {
        new Stock() { id = 1, name = "Chocolate", productType = "Sabor", quantity = "50" },
        new Stock() { id = 2, name = "Vainilla", productType = "Sabor", quantity = "50" },
        new Stock() { id = 3, name = "Red Velvet", productType = "Sabor", quantity = "50" },
        new Stock() { id = 4, name = "Almendra", productType = "Sabor", quantity = "50" },
        new Stock() { id = 5, name = "Limón", productType = "Sabor", quantity = "50" },
        new Stock() { id = 6, name = "Champagne", productType = "Sabor", quantity = "50" },
        new Stock() { id = 7, name = "Zanahoria", productType = "Sabor", quantity = "50" },
        new Stock() { id = 8, name = "Caramelo", productType = "Sabor", quantity = "50" },
        new Stock() { id = 9, name = "Calabaza", productType = "Sabor", quantity = "50" },
        new Stock() { id = 10, name = "Crema batida", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 11, name = "Fondant", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 12, name = "Buttercream", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 13, name = "Meregue", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 14, name = "Ganache", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 15, name = "Queso crema", productType = "Cobertura", quantity = "50" },
        new Stock() { id = 16, name = "Materia prima para numeros", productType = "Adorno", quantity = "50" },
        new Stock() { id = 17, name = "Materia prima para letras", productType = "Adorno", quantity = "50" },
        new Stock() { id = 18, name = "Maßteria prima para personajes", productType = "Adorno", quantity = "50" }
    };
}

<section class="py-20 bg-white">
    <div class="container max-w-6xl mx-auto">
        <h2 class="mb-4 text-4xl font-bold tracking-tight text-center">Lista de pedidos</h2>
        <div class="container justify-center mx-auto overflow-y-auto">
            <div class="flex flex-col">
                <div class="w-full">
                    <div class="border-b border-gray-200 shadow">
                        <table id="myTable">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        ID
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Proucto
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Tipo de Producto
                                    </th>
                                    <th class="px-6 py-2 text-xs text-gray-500">
                                        Cantidad
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white">
                                @foreach (var item in stocks)
                                {
                                    <tr class="whitespace-nowrap">
                                        <td class="px-6 py-4 text-sm text-gray-500">
                                            @Html.DisplayFor(modelItem => item.id)
                                        </td>
                                        <td class="px-6 py-4">
                                            <div class="text-sm text-gray-900">
                                                @Html.DisplayFor(modelItem => item.name)
                                            </div>
                                        </td>
                                        <td class="px-6 py-4">
                                            <div class="text-sm text-gray-500">
                                                @Html.DisplayFor(modelItem => item.productType)
                                            </div>
                                        </td>
                                        <td class="px-6 py-4 text-sm text-gray-500">
                                            @Html.DisplayFor(modelItem => item.quantity)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Complement.cshtml
@page
@model ComplementModel
@{
    ViewBag.Title = "Complementos";
}

<div class="grid place-items-center">
    <div class="mt-10 sm:mt-0">
        <div class="mt-5 md:mt-0">
            <div class="px-4 sm:px-0">
                <h3 class="text-center text-lg font-medium leading-6 text-gray-900">Complementa tu pastel</h3>
                <p class="text-center mt-1 text-sm text-gray-600">Puede elegir entre los diferentes adornos.</p>
                <p class="text-center mt-1 text-sm text-gray-600">(Puedes combinarlos a tu gusto)</p>
            </div>
            <form name="armar" method="post">
                <div class="shadow overflow-hidden sm:rounded-md">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                        <fieldset>
                            <div>
                                <legend class="text-base font-medium text-gray-900">Adornos</legend>
                                <p class="text-sm text-gray-500">Seleccionar el adorno o adornos de tu pastel.</p>
                                <p class="text-sm text-gray-500 text-right">(Maximo 2)</p>
                            </div>
                            <div class="mt-4 space-y-4">
                                <div class="grid grid-cols-1">
                                    <div class="flex items-start mb-2">
                                        <div class="flex items-center h-5">
                                            <input id="numeros" name="adorno" onclick="chkcontrol2(0)" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                        </div>
                                        <div class="ml-3 text-sm">
                                            <label for="numeros" class="font-medium text-gray-700">Numeros</label>
                                            <div class="mb-2 w-20 h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
                                                <img src="~/img/adorno-numeros.png">
                                            </div>
                                            <label for="valnumeros" class="block text-sm font-medium text-gray-700">Especifique (Max. 4 digitos)</label>
                                            <input type="number" name="valnumeros" id="valnumeros" placeholder="16" maxlength="4" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                        </div>
                                    </div>
                                    <div class="flex items-start mb-2">
                                        <div class="flex items-center h-5">
                                            <input id="letras" name="adorno" onclick="chkcontrol2(1)" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                        </div>
                                        <div class="ml-3 text-sm mb-2">
                                            <label for="chocolate" class="font-medium text-gray-700">Letras</label>
                                            <div class="mb-2 w-20 h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
                                                <img src="~/img/adorno-letras.png">
                                            </div>
                                            <label for="valletras" class="block text-sm font-medium text-gray-700">Especifique (Max. 30 caracteres)</label>
                                            <input type="text" name="valletras" id="valletras" placeholder="Mis dulces 16" maxlength="30" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                        </div>
                                    </div>
                                    <div class="flex items-start mb-2">
                                        <div class="flex items-center h-5">
                                            <input id="personaje" name="adorno" onclick="chkcontrol2(2)" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                        </div>
                                        <div class="ml-3 text-sm mb-2">
                                            <label for="personaje" class="font-medium text-gray-700">Personaje</label>
                                            <div class="mb-2 w-20 h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
                                                <img src="~/img/adorno-personaje.png">
                                            </div>
                                            <label for="valpersonaje" class="block text-sm font-medium text-gray-700">Especifique (Max. 30 caracteres)</label>
                                            <input type="text" name="valpersonaje" id="valpersonaje" placeholder="Spider-Man" maxlength="30" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <button asp-page-handler="Quote" asp-route-selected="@ViewBag.PastelSeleccionado" type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cotizar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Ordered.cshtml
@page
@model OrderedModel
@{
    ViewBag.Title = "Procesando Orden";
}

<div class="grid place-items-center">
    <div class="mt-10 sm:mt-0">
        <div class="px-4 sm:px-0">
            <h3 class="text-center text-lg font-medium leading-6 text-gray-900">Procesando orden y pago</h3>
            <p class="text-center mt-1 text-sm text-gray-600">Espere unos momentos.</p>
        </div>
        <div class="shadow overflow-hidden sm:rounded-md">
            <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                <div>
                    <div id="progress-bar">
                        <div id="progress"></div>
                    </div>
                </div>
            </div>
            <div id="end">
                <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                    <legend class="text-center text-base font-medium text-gray-900">Orden Procesada</legend>
                    <legend class="text-center text-sm text-gray-500">Gracias por su preferencia</legend>
                </div>
                <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                    <a asp-page="/Index" type="button" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Volver a Inicio</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/progressBarAnimation.js"></script>

mi-pasteleria/mi-pasteleria/Pages/Catalogue/Payment.cshtml
@page
@using System.Globalization;
@model PaymentModel
@{
    ViewBag.Title = "Realizar Pago";
}

<div class="grid place-items-center">
    <div class="mt-10 sm:mt-0">
        <div class="px-4 sm:px-0">
            <h3 class="text-center text-lg font-medium leading-6 text-gray-900">Selecciona la sucursal y realiza el pago</h3>
            <p class="text-center mt-1 text-sm text-gray-600">Puedes seleccionar la sucursal y método de pago de tu preferencia.</p>
        </div>
        <form name="armar" method="POST">
            <div class="shadow overflow-hidden sm:rounded-md">
                <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                    <fieldset>
                        <div>
                            <legend class="text-base font-medium text-gray-900">Método de pago</legend>
                            <p class="text-sm text-gray-500">Selecciona entre lo siguientes métodos de pago.</p>
                        </div>
                        <div class="mt-4 space-y-4">
                            <div class="grid grid-cols-2">
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="paypal" name="metodopago" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="paypal" class="font-medium text-gray-700">Paypal</label>
                                        <div class="w-20 h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
                                            <img src="~/img/metodo-paypal.png">
                                        </div>
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="mercadopago" name="metodopago" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="mercadopago" class="font-medium text-gray-700">Mercado Pago</label>
                                        <div class="w-20 h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
                                            <img src="~/img/metodo-mercadopago.png">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <div>
                            <legend class="text-base font-medium text-gray-900">Sucursal y disponibilidad</legend>
                            <p class="text-sm text-gray-500">La siguientes sucursales tienen el pastel disponible.</p>
                            <p class="text-right text-sm text-gray-500">(Disponibilidad de en sucursal para Hoy: @DateTime.Now.ToString("dd/MMMM/yyyy", new CultureInfo("es-ES"))</p>
                        </div>
                        <div class="mt-4 space-y-4">
                            <div class="grid grid-cols-1">
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="matriz" name="sucursal" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="matriz" class="font-medium text-gray-700">Matriz</label>
                                        <p class="text-sm text-gray-500">Plutarco Elías Calles 200, Viejo Roble, 66418 San Nicolás de los Garza, N.L.</p>
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="sucursal1" name="sucursal" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="sucursal1" class="font-medium text-gray-700">Sucursal 1</label>
                                        <p class="text-sm text-gray-500">Av. Republica Mexicana 400, Rincón de las Puentes, 66460 San Nicolás de los Garza, N.L.</p>
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="sucursal2" name="sucursal" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="sucursal2" class="font-medium text-gray-700">Sucursal 2</label>
                                        <p class="text-sm text-gray-500">Av. Diego Díaz de Berlanga 405, Valle de San Carlos, 66437 San Nicolás de los Garza, N.L.</p>
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="sucursal3" name="sucursal" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="sucursal3" class="font-medium text-gray-700">Sucursal 3</label>
                                        <p class="text-sm text-gray-500">Palacio de Justicia 151, Anáhuac, 66450 San Nicolás de los Garza, N.L.</p>
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="flex items-center h-5">
                                        <input id="sucursal4" name="sucursal" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                                    </div>
                                    <div class="ml-3 text-sm">
                                        <label for="sucursal4" class="font-medium text-gray-700">Sucursal 4</label>
                                        <p class="text-sm text-gray-500">Av. de la Concordia 1300, Santa Isabel, 66612 Cd Apodaca, N.L.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <div>
                            <legend class="text-base font-medium text-gray-900">Datos del cliente</legend>
                            <p class="text-sm text-gray-500">Por ultimo, requerimos estos datos para lavantar la orden.</p>
                        </div>
                        <div class="mt-4 space-y-4">
                            <div class="grid grid-cols-1">
                                <div class="flex items-start mb-2">
                                    <div class="ml-3 text-sm mb-2">
                                        <label for="nombrecliente" class="font-medium text-gray-700">Nombre</label>
                                        <input type="text" name="nombrecliente" id="valpersonaje" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="ml-3 text-sm mb-2">
                                        <label for="telefonocliente" class="font-medium text-gray-700">Telefono</label>
                                        <input type="tel" name="fechaentrega" id="telefonocliente" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    </div>
                                </div>
                                <div class="flex items-start mb-2">
                                    <div class="ml-3 text-sm mb-2">
                                        <label for="clientehorarioatencion" class="font-medium text-gray-700">Horario para contactar</label>
                                        <input type="text" name="clientehorarioatencion" id="telefonocliente" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                    <button asp-page-handler="Ordered" type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Pagar</button>
                </div>
            </div>
        </form>
    </div>
</div>